DROP TABLE IF EXISTS Personnage ;
CREATE TABLE Personnage (PersonnageId INT AUTO_INCREMENT NOT NULL,
PersonnageNom VARCHAR(25),
PersonnageImg VARCHAR(25),
Type VARCHAR(25),
PersonnageRarete INT(5),
PersonnagePvMax INT,
PersonnageLvlMax INT(50),
PRIMARY KEY (PersonnageId)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Attaque ;
CREATE TABLE Attaque (AttaqueId INT AUTO_INCREMENT NOT NULL,
AttaquePuissance INT(50),
Role INT(3),
PRIMARY KEY (AttaqueId)) ENGINE=InnoDB;

DROP TABLE IF EXISTS User ;
CREATE TABLE User (UserId INT AUTO_INCREMENT NOT NULL,
UserName VARCHAR(16),
UserPassword VARCHAR(30),
UserMail VARCHAR(255),
PRIMARY KEY (UserId)) ENGINE=InnoDB;

DROP TABLE IF EXISTS UserItem ;
CREATE TABLE UserItem (UserItemId INT AUTO_INCREMENT NOT NULL,
UserItemMoney BIGINT,
UserItemCrystal BIGINT,
UserItemUpgradeAbility BIGINT,
PRIMARY KEY (UserItemId)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Modifyer ;
CREATE TABLE Modifyer (ModifyerId INT AUTO_INCREMENT NOT NULL,
ModifyerNom VARCHAR(25),
ModifyerDescription VARCHAR(255),
ModifyerDuree INT(3),
PRIMARY KEY (ModifyerId)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Possede ;
CREATE TABLE Possede (PossedeId INT AUTO_INCREMENT NOT NULL,
AttaqueId INT NOT NULL,
PRIMARY KEY (PossedeId)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Appliques ;
CREATE TABLE Appliques (AppliquesId INT AUTO_INCREMENT NOT NULL,
ModifyerId INT NOT NULL,
PRIMARY KEY (AppliquesId))ENGINE=InnoDB;

DROP TABLE IF EXISTS EstDeNiv ;
CREATE TABLE EstDeNiv (EstDeNivId INT AUTO_INCREMENT NOT NULL,
UserItemId INT NOT NULL,
PersonnageId INT NOT NULL,
Niveau INT(50),
PRIMARY KEY (EstDeNivId)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Appartiens ;
CREATE TABLE Appartiens (AppartiensId INT AUTO_INCREMENT NOT NULL,
ItemId INT NOT NULL,
UserId INT NOT NULL,
PRIMARY KEY (AppartiensId)) ENGINE=InnoDB;

ALTER TABLE Possede ADD CONSTRAINT PossedeId FOREIGN KEY (PossedeId) REFERENCES Attaque (AttaqueId);
ALTER TABLE Appliques ADD CONSTRAINT ModifyerId FOREIGN KEY (ModifyerId) REFERENCES Modifyer (ModifyerId);
ALTER TABLE EstDeNiv ADD CONSTRAINT PersonnageId FOREIGN KEY (PersonnageId) REFERENCES Personnage (PersonnageId);
ALTER TABLE EstDeNiv ADD CONSTRAINT UserItemId FOREIGN KEY (UserItemId) REFERENCES UserItem (UserItemId);
ALTER TABLE Appartiens ADD CONSTRAINT UserId FOREIGN KEY (UserId) REFERENCES User (UserId);
ALTER TABLE Appartiens ADD CONSTRAINT ItemId FOREIGN KEY (ItemId) REFERENCES UserItem (UserItemId);